#!/bin/bash
# Auto-detect local IP and update .env before starting Expo

# Get local IP (works on macOS and Linux)
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')

if [ -z "$LOCAL_IP" ]; then
  echo "❌ Could not detect local IP address"
  exit 1
fi

SERVER_PORT=${SERVER_PORT:-5001}

echo "🔍 Detected local IP: $LOCAL_IP"
echo "📡 Server port: $SERVER_PORT"

# Update .env file
cat > .env << EOF
# Auto-generated by start.sh — do not edit manually
# Machine IP detected at: $(date)
EXPO_PUBLIC_API_URL=http://${LOCAL_IP}:${SERVER_PORT}/api
EXPO_PUBLIC_SOCKET_URL=http://${LOCAL_IP}:${SERVER_PORT}
EOF

echo "✅ Updated .env:"
cat .env
echo ""

# Start Expo
npx expo start --clear "$@"
